FROM scratch

COPY . /

LABEL org.opencontainers.image.title="Hermes sandbox kit" \
      org.opencontainers.image.description="OCI-packaged Hermes sandbox kit" \
      org.opencontainers.image.source="https://github.com/vskh-docker-images/sandbox-templates"
